ground_truth_path: "/Users/leonardoalchieri/Datasets/OMGEmotionChallenge/omg_ValidationVideos.csv"
data_path: "/Users/leonardoalchieri/Datasets/OMGEmotionChallenge/Validation_Set/trimmed_faces"
output_name: validation_list_lstm.txt